/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MonthlyRecord, IncidenciaDetail, ProjectSettings, DashboardWidgetConfig } from './types';

export const INITIAL_MONTHLY_RECORDS: MonthlyRecord[] = [
  {
    month: 'enero',
    PLO: { programado: 9, realizado: 9 },
    RACA: { programado: 27, realizado: 27 },
    RACO: { programado: 12, realizado: 12 },
    incidencesCount: 1,
  },
  {
    month: 'febrero',
    PLO: { programado: 9, realizado: 9 },
    RACA: { programado: 41, realizado: 41 },
    RACO: { programado: 10, realizado: 10 },
    incidencesCount: 0,
  },
  {
    month: 'marzo',
    PLO: { programado: 13, realizado: 13 },
    RACA: { programado: 26, realizado: 26 },
    RACO: { programado: 23, realizado: 23 },
    incidencesCount: 0,
  },
  {
    month: 'abril',
    PLO: { programado: 11, realizado: 11 },
    RACA: { programado: 27, realizado: 27 },
    RACO: { programado: 19, realizado: 19 },
    incidencesCount: 1,
  },
  {
    month: 'mayo',
    PLO: { programado: 12, realizado: 12 },
    RACA: { programado: 41, realizado: 41 },
    RACO: { programado: 16, realizado: 16 },
    incidencesCount: 2,
  },
  {
    month: 'junio',
    PLO: { programado: 11, realizado: 11 },
    RACA: { programado: 32, realizado: 32 },
    RACO: { programado: 17, realizado: 17 },
    incidencesCount: 1,
  },
  {
    month: 'julio',
    PLO: { programado: 11, realizado: 0 },
    RACA: { programado: 23, realizado: 0 },
    RACO: { programado: 14, realizado: 0 },
    incidencesCount: 0,
  },
  {
    month: 'agosto',
    PLO: { programado: 9, realizado: 0 },
    RACA: { programado: 28, realizado: 0 },
    RACO: { programado: 19, realizado: 0 },
    incidencesCount: 0,
  },
  {
    month: 'septiembre',
    PLO: { programado: 11, realizado: 0 },
    RACA: { programado: 45, realizado: 0 },
    RACO: { programado: 14, realizado: 0 },
    incidencesCount: 0,
  },
  {
    month: 'octubre',
    PLO: { programado: 12, realizado: 0 },
    RACA: { programado: 32, realizado: 0 },
    RACO: { programado: 23, realizado: 0 },
    incidencesCount: 0,
  },
  {
    month: 'noviembre',
    PLO: { programado: 15, realizado: 0 },
    RACA: { programado: 30, realizado: 0 },
    RACO: { programado: 22, realizado: 0 },
    incidencesCount: 0,
  },
  {
    month: 'diciembre',
    PLO: { programado: 3, realizado: 0 },
    RACA: { programado: 11, realizado: 0 },
    RACO: { programado: 3, realizado: 0 },
    incidencesCount: 0,
  },
];

export const INITIAL_INCIDENCIAS_DETAILS: IncidenciaDetail[] = [
  {
    id: 'inc-h1',
    month: 'mayo',
    subsystem: 'TELEMANDO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia de telemando en Villena (VLN) / Vía 1: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '784 | 2017',
    fecha: '14/05/2017',
    tecnica: 'Telemando',
    ubicacion: 'Villena (VLN) / Vía 1',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h2',
    month: 'mayo',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia de climatización RACA en Campanario_312 / Vía 2: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '909 | 2017',
    fecha: '31/05/2017',
    tecnica: 'R.A.C.A',
    ubicacion: 'Campanario_312 / Vía 2',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h3',
    month: 'junio',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia de climatización RACA en ATI_311.5 / Vía 2: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '937 | 2017',
    fecha: '05/06/2017',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI_311.5 / Vía 2',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h4',
    month: 'junio',
    subsystem: 'RACO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia en Bif. Aguaverde: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '938 | 2017',
    fecha: '05/06/2017',
    tecnica: 'R.A.C.O',
    ubicacion: 'Bif. Aguaverde',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h5',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de climatización RACA en ATF_321.1 / Vía 1: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1104 | 2017',
    fecha: '01/07/2017',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATF_321.1 / Vía 1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h6',
    month: 'julio',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en Sax_321 / Vía 1: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1181 | 2017',
    fecha: '12/07/2017',
    tecnica: 'Telemando',
    ubicacion: 'Sax_321 / Vía 1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h7',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia RACA en Sax_321 / Vía 1: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1196 | 2017',
    fecha: '13/07/2017',
    tecnica: 'R.A.C.A',
    ubicacion: 'Sax_321 / Vía 1',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h8',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en Bonete: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1248 | 2017',
    fecha: '19/07/2017',
    tecnica: 'R.A.C.A',
    ubicacion: 'Bonete',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h9',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia RACA en 438+478 / Vía 1: Cerrado',
    tiempoPresenciaMin: 50,
    tiempoReparacionMin: 130,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1291 | 2017',
    fecha: '21/07/2017',
    tecnica: 'R.A.C.A',
    ubicacion: '438+478 / Vía 1',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h10',
    month: 'julio',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Monforte del Cid: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1335 | 2017',
    fecha: '31/07/2017',
    tecnica: 'R.A.C.O',
    ubicacion: 'Monforte del Cid',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h11',
    month: 'agosto',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Chinchilla: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1390 | 2017',
    fecha: '07/08/2017',
    tecnica: 'R.A.C.O',
    ubicacion: 'Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h12',
    month: 'enero',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Chinchilla: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '9 | 2018',
    fecha: '03/01/2018',
    tecnica: 'R.A.C.O',
    ubicacion: 'Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h13',
    month: 'febrero',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en Bif. Murcia: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '225 | 2018',
    fecha: '14/02/2018',
    tecnica: 'R.A.C.A',
    ubicacion: 'Bif. Murcia',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h14',
    month: 'febrero',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en PAET Villena: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '245 | 2018',
    fecha: '20/02/2018',
    tecnica: 'Telemando',
    ubicacion: 'PAET Villena',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h15',
    month: 'abril',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia RACA en S.E. Campanario_312: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '483 | 2018',
    fecha: '07/04/2018',
    tecnica: 'R.A.C.A',
    ubicacion: 'S.E. Campanario_312',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h16',
    month: 'mayo',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATF_312.1: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '717/2018',
    fecha: '17/05/2018',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATF_312.1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h17',
    month: 'mayo',
    subsystem: 'RACA',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia RACA en ATF_312.1: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '799/2018',
    fecha: '27/05/2018',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATF_312.1',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h18',
    month: 'junio',
    subsystem: 'RACO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia RACO en Bif. Aguaverde: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '844 | 2018',
    fecha: '04/06/2018',
    tecnica: 'R.A.C.O',
    ubicacion: 'Bif. Aguaverde',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h19',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia RACA en ATI 312.3: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 130,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1116/2018',
    fecha: '11/07/2018',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 312.3',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h20',
    month: 'octubre',
    subsystem: 'RACA',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia RACA en ATI_321.4: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1652/2018',
    fecha: '09/10/2018',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI_321.4',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h21',
    month: 'octubre',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en PICV 343: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1726/2018',
    fecha: '23/10/2018',
    tecnica: 'R.A.C.O',
    ubicacion: 'PICV 343',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h22',
    month: 'enero',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI_321.4: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '13/2019',
    fecha: '03/01/2019',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI_321.4',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h23',
    month: 'mayo',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Pb Bifurcación Vinalopó: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '745/2019',
    fecha: '23/05/2019',
    tecnica: 'R.A.C.O',
    ubicacion: 'Pb Bifurcación Vinalopó',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h24',
    month: 'junio',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en PAET Chinchilla: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '927/2019',
    fecha: '24/06/2019',
    tecnica: 'R.A.C.O',
    ubicacion: 'PAET Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h25',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia RACA en S.E. 312/PAET Bonete321.1: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 130,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1369/2019',
    fecha: '02/09/2019',
    tecnica: 'R.A.C.A',
    ubicacion: 'S.E. 312/PAET Bonete321.1',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h26',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia RACA en ATI 321.4: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1430/2019',
    fecha: '13/09/2019',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 321.4',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h27',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 312.5: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1432/2019',
    fecha: '04/09/2019',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 312.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h28',
    month: 'octubre',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en ATI 312.5: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1656/2019',
    fecha: '21/10/2019',
    tecnica: 'Telemando',
    ubicacion: 'ATI 312.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h29',
    month: 'marzo',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Monforte del Cid: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '410/2020',
    fecha: '30/03/2020',
    tecnica: 'R.A.C.O',
    ubicacion: 'Monforte del Cid',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h30',
    month: 'abril',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en Chinchilla (CHN): Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '432/2020',
    fecha: '06/04/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'Chinchilla (CHN)',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h31',
    month: 'abril',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en Campanario_312 / Vía 2: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '513/2020',
    fecha: '26/04/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'Campanario_312 / Vía 2',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h32',
    month: 'mayo',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Villena: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '655/2020',
    fecha: '19/05/2020',
    tecnica: 'R.A.C.O',
    ubicacion: 'Villena',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h33',
    month: 'junio',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Bif. La Oliva: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '867/2020',
    fecha: '26/06/2020',
    tecnica: 'R.A.C.O',
    ubicacion: 'Bif. La Oliva',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h34',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 312.5: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '943/2020',
    fecha: '09/07/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 312.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h35',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en BLO-CA1: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1060/2020',
    fecha: '29/07/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'BLO-CA1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h36',
    month: 'agosto',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATF 321.1: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1196/2020',
    fecha: '21/08/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATF 321.1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h37',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en SE 312: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1302/2020',
    fecha: '18/09/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'SE 312',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h38',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en PAET Villena: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 105,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1314/2020',
    fecha: '22/09/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'PAET Villena',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h39',
    month: 'octubre',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Bonete: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1369/2020',
    fecha: '01/10/2020',
    tecnica: 'R.A.C.O',
    ubicacion: 'Bonete',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h40',
    month: 'octubre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en SAX 321: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1429/2020',
    fecha: '08/10/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'SAX 321',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h41',
    month: 'octubre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en Caudete: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1458/2020',
    fecha: '15/10/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'Caudete',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h42',
    month: 'diciembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en SE Campanario: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1901/2020',
    fecha: '28/12/2020',
    tecnica: 'R.A.C.A',
    ubicacion: 'SE Campanario',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h43',
    month: 'enero',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 321.6: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '59/2021',
    fecha: '15/01/2021',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 321.6',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h44',
    month: 'mayo',
    subsystem: 'RACA',
    tipo: 'AJENAS',
    descripcion: 'Incidencia RACA en ATI 312.5: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '681/2021',
    fecha: '05/05/2021',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 312.5',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h45',
    month: 'junio',
    subsystem: 'RACA',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia RACA en ATI 321.1: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1049/2021',
    fecha: '24/06/2021',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 321.1',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h46',
    month: 'agosto',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en PB Caudete: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1359/2021',
    fecha: '06/08/2021',
    tecnica: 'Telemando',
    ubicacion: 'PB Caudete',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h47',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 311.5: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1526/2021',
    fecha: '01/09/2021',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 311.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h48',
    month: 'septiembre',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Las Chozas: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1668/2021',
    fecha: '28/09/2021',
    tecnica: 'R.A.C.O',
    ubicacion: 'Las Chozas',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h49',
    month: 'octubre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 311.5: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 105,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1871/2021',
    fecha: '29/10/2021',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 311.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h50',
    month: 'noviembre',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en ET Alicante: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 80,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1995/2021',
    fecha: '18/11/2021',
    tecnica: 'Telemando',
    ubicacion: 'ET Alicante',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h51',
    month: 'diciembre',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en PAET Chinchilla: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 115,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '2274/2021',
    fecha: '29/12/2021',
    tecnica: 'R.A.C.O',
    ubicacion: 'PAET Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h52',
    month: 'enero',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATF 321.1: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '124/2022',
    fecha: '18/01/2022',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATF 321.1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h53',
    month: 'mayo',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en VLN-CA2: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '772/2022',
    fecha: '06/05/2022',
    tecnica: 'Telemando',
    ubicacion: 'VLN-CA2',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h54',
    month: 'mayo',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI_321.3: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '927/2022',
    fecha: '30/05/2022',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI_321.3',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h55',
    month: 'junio',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en ATI 321.5: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '941/2022',
    fecha: '01/06/2022',
    tecnica: 'Telemando',
    ubicacion: 'ATI 321.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h56',
    month: 'agosto',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en ATI 311.5: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1349/2022',
    fecha: '09/08/2022',
    tecnica: 'Telemando',
    ubicacion: 'ATI 311.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h57',
    month: 'septiembre',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando RACO en PCA Alcoraya_ACY: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1564/2022',
    fecha: '06-09-2022',
    tecnica: 'Telemando RACO',
    ubicacion: 'PCA Alcoraya_ACY',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h58',
    month: 'marzo',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando RACO en SE Sax_321: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '494/2023',
    fecha: '26/03/2023',
    tecnica: 'Telemando RACO',
    ubicacion: 'SE Sax_321',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h59',
    month: 'marzo',
    subsystem: 'RACO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia de telemando RACO en SE Sax_321: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '495/2023',
    fecha: '26/03/2023',
    tecnica: 'Telemando RACO',
    ubicacion: 'SE Sax_321',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h60',
    month: 'mayo',
    subsystem: 'TELEMANDO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia de telemando en PC Alcoraya: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '784/2023',
    fecha: '18/05/2023',
    tecnica: 'Telemando',
    ubicacion: 'PC Alcoraya',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h61',
    month: 'junio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en PICV 343: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '877/2023',
    fecha: '06/06/2023',
    tecnica: 'R.A.C.A',
    ubicacion: 'PICV 343',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h62',
    month: 'septiembre',
    subsystem: 'RACO',
    tipo: 'AJENAS',
    descripcion: 'Incidencia de telemando RACO en ATF 312.1: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 130,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1641/2023',
    fecha: '14/09/2023',
    tecnica: 'Telemando RACO',
    ubicacion: 'ATF 312.1',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h63',
    month: 'septiembre',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Chinchilla: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1652/2023',
    fecha: '15/09/2023',
    tecnica: 'R.A.C.O',
    ubicacion: 'Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h64',
    month: 'septiembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en SE 312: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1720/2023',
    fecha: '26/09/2023',
    tecnica: 'R.A.C.A',
    ubicacion: 'SE 312',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h65',
    month: 'octubre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en SE 312: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1864/2023',
    fecha: '19/10/2023',
    tecnica: 'R.A.C.A',
    ubicacion: 'SE 312',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h66',
    month: 'diciembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ET Chinchilla: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '2240/2023',
    fecha: '14/12/2023',
    tecnica: 'R.A.C.A',
    ubicacion: 'ET Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h67',
    month: 'diciembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en PCA Atalaya: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '2247/2023',
    fecha: '15/12/2023',
    tecnica: 'R.A.C.A',
    ubicacion: 'PCA Atalaya',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h68',
    month: 'diciembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 311.5: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '2322/2023',
    fecha: '29/12/2023',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 311.5',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h69',
    month: 'enero',
    subsystem: 'RACA',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia RACA en 63.000 / 112: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '112',
    fecha: '19/01/2024',
    tecnica: 'R.A.C.A 63.000 / 112',
    ubicacion: '112',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h70',
    month: 'marzo',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando RACO en PCA Atalaya: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '425/2024',
    fecha: '10/03/2024',
    tecnica: 'Telemando RACO',
    ubicacion: 'PCA Atalaya',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h71',
    month: 'mayo',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en PICV 343: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '760/2024',
    fecha: '27/05/2024',
    tecnica: 'R.A.C.O',
    ubicacion: 'PICV 343',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h72',
    month: 'julio',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en PCA EL Salabrejo_ESB: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1003/2024',
    fecha: '04/07/2024',
    tecnica: 'Telemando',
    ubicacion: 'PCA EL Salabrejo_ESB',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h73',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI 312.2: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1039/2024',
    fecha: '11/07/2024',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI 312.2',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h74',
    month: 'octubre',
    subsystem: 'TELEMANDO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia de telemando en Bonete: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1514/2024',
    fecha: '08/10/2024',
    tecnica: 'Telemando',
    ubicacion: 'Bonete',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h75',
    month: 'octubre',
    subsystem: 'TELEMANDO',
    tipo: 'AJENAS',
    descripcion: 'Incidencia de telemando en Bonete: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1616/2024',
    fecha: '26/10/2024',
    tecnica: 'Telemando',
    ubicacion: 'Bonete',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h76',
    month: 'noviembre',
    subsystem: 'TELEMANDO',
    tipo: 'AJENAS',
    descripcion: 'Incidencia de telemando en Chinchilla: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '2332',
    fecha: '29/11/2024',
    tecnica: 'Telemando',
    ubicacion: 'Chinchilla',
    imputacion: 'Ajena',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h77',
    month: 'diciembre',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en Caudete: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1850/2024',
    fecha: '06/12/2024',
    tecnica: 'Telemando',
    ubicacion: 'Caudete',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h78',
    month: 'febrero',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en PAET Chinchilla: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '213/2025',
    fecha: '13/02/2025',
    tecnica: 'Telemando',
    ubicacion: 'PAET Chinchilla',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h79',
    month: 'abril',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en PICV 442: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '510/2025',
    fecha: '14/04/2025',
    tecnica: 'R.A.C.O',
    ubicacion: 'PICV 442',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h80',
    month: 'abril',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en PICV 343: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 100,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '512/2005',
    fecha: '14/04/2025',
    tecnica: 'R.A.C.O',
    ubicacion: 'PICV 343',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h81',
    month: 'junio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI_312.2: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 90,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '861/2025',
    fecha: '11/06/2025',
    tecnica: 'R.A.C.A',
    ubicacion: 'ATI_312.2',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h82',
    month: 'julio',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en Campanario_312: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1045/2025',
    fecha: '15/07/2025',
    tecnica: 'RACA',
    ubicacion: 'Campanario_312',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h83',
    month: 'agosto',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en PCA SALOBREJO: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1181/2025',
    fecha: '09/08/2025',
    tecnica: 'Telemando',
    ubicacion: 'PCA SALOBREJO',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h84',
    month: 'agosto',
    subsystem: 'TELEMANDO',
    tipo: 'A TERCEROS',
    descripcion: 'Incidencia de telemando en ATI 312.2: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1189/2025',
    fecha: '12/08/2025',
    tecnica: 'Telemando',
    ubicacion: 'ATI 312.2',
    imputacion: 'A Terceros',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h85',
    month: 'octubre',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en BVN: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1480/2025',
    fecha: '06/10/2025',
    tecnica: 'Telemando',
    ubicacion: 'BVN',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h86',
    month: 'diciembre',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATI_321.7: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '1778/2025',
    fecha: '01/12/2025',
    tecnica: 'RACA',
    ubicacion: 'ATI_321.7',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h87',
    month: 'enero',
    subsystem: 'RACO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACO en Las Chozas: Cerrado',
    tiempoPresenciaMin: 35,
    tiempoReparacionMin: 110,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '66/2026 (*)',
    fecha: '15/01/2026',
    tecnica: 'RACO',
    ubicacion: 'Las Chozas',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h88',
    month: 'abril',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en Las Chozas: Cerrado',
    tiempoPresenciaMin: 40,
    tiempoReparacionMin: 120,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '618/2026',
    fecha: '21/04/2026',
    tecnica: 'Telemando',
    ubicacion: 'Las Chozas',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h89',
    month: 'mayo',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en Las Chozas: Cerrado',
    tiempoPresenciaMin: 30,
    tiempoReparacionMin: 85,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '698/2026 (*)',
    fecha: '04/05/2026',
    tecnica: 'Telemando',
    ubicacion: 'Las Chozas',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h90',
    month: 'mayo',
    subsystem: 'RACA',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia RACA en ATF 321.1: Cerrado',
    tiempoPresenciaMin: 45,
    tiempoReparacionMin: 95,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '842/2026',
    fecha: '31/05/2026',
    tecnica: 'RACA',
    ubicacion: 'ATF 321.1',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  },
  {
    id: 'inc-h91',
    month: 'junio',
    subsystem: 'TELEMANDO',
    tipo: 'PROPIAS',
    descripcion: 'Incidencia de telemando en Bif. Aguarverde: Cerrado',
    tiempoPresenciaMin: 50,
    tiempoReparacionMin: 140,
    trenesAfectados: 0,
    retrasosMin: 0,
    numeroIncidencia: '927/2026 (*)',
    fecha: '16/06/2026',
    tecnica: 'Telemando',
    ubicacion: 'Bif. Aguarverde',
    imputacion: 'Propia',
    observaciones: 'Cerrado'
  }
];

export const DEFAULT_SETTINGS: ProjectSettings = {
  maxPenalizacionesAnuales: 9,
  thresholdPresenciaMin: 90,
  thresholdReparacionMin: 240, // 4 hours
  thresholdRetrasoMin: 15,
  currentMonth: 'junio',
  contractor: 'TELICE',
  ambitos: ['BM. MDC', 'BM. RQU', 'BM. VRU'],
  observaciones: 'Sincronización en tiempo real activa. Mantenimiento al día con un 100% de consecución para el periodo transcurrido.',
};

export const DEFAULT_WIDGETS: DashboardWidgetConfig[] = [
  { id: 'preventivos-mensual', title: 'Preventivos Mensual', visible: true, order: 1 },
  { id: 'preventivos-anual', title: 'Preventivo Anual', visible: true, order: 2 },
  { id: 'incidencias', title: 'Fiabilidad', visible: true, order: 3 },
  { id: 'materiales', title: 'Materiales', visible: true, order: 4 },
  { id: 'penalizaciones', title: 'Indicadores', visible: true, order: 5 },
  { id: 'cuadro-mando', title: 'Cuadro de Mando', visible: true, order: 6 },
  { id: 'source-data', title: 'Origen de Datos', visible: true, order: 7 },
];

export const DEFAULT_MATERIALES = [
  {
    id: 'mat-h1',
    numeroIncidencia: '784 | 2017',
    fecha: '14/05/2017',
    tecnica: 'TELEMANDO',
    imputacion: 'A terceros',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Interruptor diferencial SE ID 2P 40A AC 300mA (Ref. A9R84240)',
    cantidad: 1
  },
  {
    id: 'mat-h2',
    numeroIncidencia: '938 | 2017',
    fecha: '05/06/2017',
    tecnica: 'RACO',
    imputacion: 'A terceros',
    codMaterial: '731900002',
    descripcion: 'CONVERTIDOR RS-232/RS485 a FO 12VDC Cr2f.A1.f1.d1 (CR2F)',
    cantidad: 1
  },
  {
    id: 'mat-h3',
    numeroIncidencia: '1248 | 2017',
    fecha: '19/07/2017',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Empalme mecánico KeyQuick',
    cantidad: 1
  },
  {
    id: 'mat-h4',
    numeroIncidencia: '1390 | 2017',
    fecha: '07/08/2017',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'Mod SAITEL 100SM',
    cantidad: 1
  },
  {
    id: 'mat-h5',
    numeroIncidencia: '9 | 2018',
    fecha: '03/01/2018',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'Mod SAITEL 100SM M54022121',
    cantidad: 1
  },
  {
    id: 'mat-h6',
    numeroIncidencia: '225 | 2018',
    fecha: '14/02/2018',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h7',
    numeroIncidencia: '717 | 2018',
    fecha: '17/05/2018',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h8',
    numeroIncidencia: '1652 | 2018',
    fecha: '09/10/2018',
    tecnica: 'RACA',
    imputacion: 'A terceros',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h9',
    numeroIncidencia: '1726 | 2018',
    fecha: '23/10/2018',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h10',
    numeroIncidencia: '13 | 2019',
    fecha: '03/01/2019',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900002',
    descripcion: 'CR2F',
    cantidad: 1
  },
  {
    id: 'mat-h11',
    numeroIncidencia: '927 | 2019',
    fecha: '24/06/2019',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h12',
    numeroIncidencia: '1432 / 2019',
    fecha: '04/09/2019',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'SAITEL Ondulador Averiado',
    cantidad: 1
  },
  {
    id: 'mat-h13',
    numeroIncidencia: '1656 / 2019',
    fecha: '21/10/2019',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h14',
    numeroIncidencia: '432 / 2020',
    "fecha": "06/04/2020",
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h15',
    numeroIncidencia: '1060 / 2020',
    fecha: '29/07/2020',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h16',
    numeroIncidencia: '1302 / 2020',
    fecha: '18/09/2020',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h17',
    numeroIncidencia: '1302 / 2020 (Bis)',
    fecha: '18/09/2020',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h18',
    numeroIncidencia: '1429 / 2020',
    fecha: '08/10/2020',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Relé',
    cantidad: 1
  },
  {
    id: 'mat-h19',
    numeroIncidencia: '1901 / 2020*',
    fecha: '28/12/2020',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900002',
    descripcion: 'CONVERTIDOR RS-232/RS485 a FO 12VDC Cr2f.A1.f1.d1 (CR2F)',
    cantidad: 1
  },
  {
    id: 'mat-h20',
    numeroIncidencia: '1901 / 2020*',
    fecha: '28/12/2020',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h21',
    numeroIncidencia: '569 / 2021',
    fecha: '16/04/2021',
    tecnica: 'TELEMANDO',
    imputacion: 'A terceros',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Ondulador Salicru CS-3000 IS-B/D-230',
    cantidad: 1
  },
  {
    id: 'mat-h22',
    numeroIncidencia: '1526 / 2021',
    fecha: '01/09/2021',
    tecnica: 'RACA',
    imputacion: 'A terceros',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h23',
    numeroIncidencia: '2274 / 2021',
    fecha: '29/12/2021',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Relé',
    cantidad: 1
  },
  {
    id: 'mat-h24',
    numeroIncidencia: '124 / 2022',
    fecha: '18/01/2022',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900002',
    descripcion: 'CONVERTIDOR RS-232/RS485 a FO 12VDC Cr2f.A1.f1.d1 (CR2F)',
    cantidad: 1
  },
  {
    id: 'mat-h25',
    numeroIncidencia: '772 / 2022',
    fecha: '06/05/2022',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900000',
    descripcion: 'MOD. SAICOM E V2.R1.D3',
    cantidad: 1
  },
  {
    id: 'mat-h26',
    numeroIncidencia: '927 / 2022',
    fecha: '30/05/2022',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h27',
    numeroIncidencia: '941 / 2022',
    fecha: '01/06/2022',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900002',
    descripcion: 'CR2F',
    cantidad: 1
  },
  {
    id: 'mat-h28',
    numeroIncidencia: '1349 / 2022',
    fecha: '09/08/2022',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h29',
    numeroIncidencia: '1564 / 2022',
    fecha: '06/09/2022',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'Mod SAITEL 100SM M54022121',
    cantidad: 1
  },
  {
    id: 'mat-h30',
    numeroIncidencia: '784 / 2023',
    fecha: '18/05/2023',
    tecnica: 'RACO',
    imputacion: 'A terceros',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h31',
    numeroIncidencia: '877 / 2023',
    fecha: '06/06/2023',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h32',
    numeroIncidencia: '1641 / 2023',
    fecha: '14/09/2023',
    tecnica: 'TELEMANDO',
    imputacion: 'A terceros',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h33',
    numeroIncidencia: '1652 / 2023',
    fecha: '15/09/2023',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900002',
    descripcion: 'CR2F',
    cantidad: 1
  },
  {
    id: 'mat-h34',
    numeroIncidencia: '2240 | 2023',
    fecha: '14/12/2023',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Relé',
    cantidad: 1
  },
  {
    id: 'mat-h35',
    numeroIncidencia: '2247 | 2023',
    fecha: '15/12/2023',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h36',
    numeroIncidencia: '2322 | 2023',
    fecha: '29/12/2023',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Relé',
    cantidad: 1
  },
  {
    id: 'mat-h37',
    numeroIncidencia: '112',
    fecha: '19/01/2024',
    tecnica: 'RACA',
    imputacion: 'A terceros',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h38',
    numeroIncidencia: '425 | 2024',
    fecha: '13/03/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h39',
    numeroIncidencia: '760 / 2024',
    fecha: '27/05/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h40',
    numeroIncidencia: '1003 / 2024',
    fecha: '04/07/2024',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Placa Saitel',
    cantidad: 1
  },
  {
    id: 'mat-h41',
    numeroIncidencia: '1039 / 2024',
    fecha: '11/07/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h42',
    numeroIncidencia: '1514 / 2024',
    fecha: '08/10/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Ajena',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 3
  },
  {
    id: 'mat-h43',
    numeroIncidencia: '1514 / 2024 (2)',
    fecha: '08/10/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Ajena',
    codMaterial: '731900000',
    descripcion: 'SAICOM TELICE BECKHOFF',
    cantidad: 1
  },
  {
    id: 'mat-h44',
    numeroIncidencia: '1514 / 2024 (3)',
    fecha: '08/10/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Ajena',
    codMaterial: '731900002',
    descripcion: 'CR2F',
    cantidad: 2
  },
  {
    id: 'mat-h45',
    numeroIncidencia: '2332',
    fecha: '29/11/2024',
    tecnica: 'TELEMANDO',
    imputacion: 'Ajena',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h46',
    numeroIncidencia: '510 / 2025',
    fecha: '14/02/2025',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h47',
    numeroIncidencia: '512 / 2005',
    fecha: '14/05/2025',
    tecnica: 'RACO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h48',
    numeroIncidencia: '861 / 2025',
    fecha: '11/06/2025',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900002',
    descripcion: 'CR2F',
    cantidad: 1
  },
  {
    id: 'mat-h49',
    numeroIncidencia: '1045 / 2025',
    fecha: '15/07/2025',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  },
  {
    id: 'mat-h50',
    numeroIncidencia: '1181 / 2025',
    fecha: '09/08/2025',
    tecnica: 'TELEMANDO',
    imputacion: 'Propia',
    codMaterial: '731900005',
    descripcion: 'SAITEL',
    cantidad: 1
  },
  {
    id: 'mat-h51',
    numeroIncidencia: '1189 / 2025',
    fecha: '12/08/2025',
    tecnica: 'TELEMANDO',
    imputacion: 'A terceros',
    codMaterial: '731900002',
    descripcion: 'CR2F',
    cantidad: 1
  },
  {
    id: 'mat-h52',
    numeroIncidencia: '1480 / 2025',
    fecha: '06/10/2025',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900006',
    descripcion: 'uTrack',
    cantidad: 1
  },
  {
    id: 'mat-h53',
    numeroIncidencia: '1778 / 2025',
    fecha: '01/12/2025',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: 'No Cód. SAP',
    descripcion: 'Ondulador Salicru CS-3000 IS-B/D-230',
    cantidad: 1
  },
  {
    id: 'mat-h54',
    numeroIncidencia: '842 / 2026',
    fecha: '31/05/2026',
    tecnica: 'RACA',
    imputacion: 'Propia',
    codMaterial: '731900012',
    descripcion: 'Contactor Carlo Gavazzi RJ1A23D30E',
    cantidad: 1
  }
];

export const CONTRACTOR_OPTIONS = [
  'TELICE',
  'TELICESA',
  'MANTENIMIENTO UTE REQUENA',
  'SIEMENS RAIL AUTOMATION S.A.',
  'SYSTEM, S.A.',
  'UTE AVE Energía',
  'UTE BASES Villarrubia-Gabaldón',
  'UTE CHAMARTÍN-TORREJON DE...',
  'UTE MAVENTS',
  'UTE SALAVE (CPP)',
];

export const AMBITO_OPTIONS = ['BM. GAB', 'BM. MDC', 'BM. RQU', 'BM. VRU'];

export const MONTH_LABELS: Record<string, string> = {
  enero: 'Enero',
  febrero: 'Febrero',
  marzo: 'Marzo',
  abril: 'Abril',
  mayo: 'Mayo',
  junio: 'Junio',
  julio: 'Julio',
  agosto: 'Agosto',
  septiembre: 'Septiembre',
  octubre: 'Octubre',
  noviembre: 'Noviembre',
  diciembre: 'Diciembre',
};
